---
version: '3'

services:
  node:
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000"

networks:
  default:
    external:
      name: netlify_oauth_default
